name: APTrans
favicon: null
layout_spectrum: 0.3537276783026755
typography_spectrum: 0.7301191671285778
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.12121568224392831
  lightness: 0.44699917640537024
  saturation: 0.2804840332828462
  rhythmicContrast: 0.029569199308753014
purpose: []
